#ifdef BOARD_AB_SMARTHOUSE_SA_REG6_8CH
    #define DEVICE_ID "AB-SWA-8CH"
    #define HARDWARE_NAME "AB-SWA-8CH"
    #define DEVICE_NAME "AB-SmartHouse Switch Actuator 8x, 6 TE"

    #define INFO_LED_PIN 11
    #define INFO_LED_PIN_ACTIVE_ON HIGH
    #define PROG_LED_PIN 10
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN 9
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

    #define KNX_UART_NUM 0
    #define KNX_UART_TX_PIN 12
    #define KNX_UART_RX_PIN 13
    #define SAVE_INTERRUPT_PIN 0

    #define OPENKNX_SWA_CHANNEL_COUNT 8
    #define OPENKNX_SWA_SET_PINS 2, 26, 24, 22, 20 ,18, 16, 14
    #define OPENKNX_SWA_RESET_PINS 3, 27, 25, 23, 21, 19, 17, 15
    #define OPENKNX_SWA_SET_ACTIVE_ON HIGH
    #define OPENKNX_SWA_RESET_ACTIVE_ON HIGH
    #define OPENKNX_SWA_BISTABLE_IMPULSE_LENGTH 50
    #define OPENKNX_SWA_HAS_FRONT_PLATE

    #define OPENKNX_SWA_STATUS_PINS 0x0100, 0x0101, 0x0102, 0x0103, 0x0104, 0x0105, 0x0106, 0x0107
    #define OPENKNX_SWA_STATUS_ACTIVE_ON HIGH
    #define OPENKNX_SWA_SWITCH_PINS 0x0115, 0x0114, 0x0113, 0x0112, 0x0111, 0x0110, 0x0109, 0x0108
    #define OPENKNX_SWA_SWITCH_ACTIVE_ON LOW

    #define OPENKNX_SWA_VOLTAGE_SENSE_PIN 29

    #define OPENKNX_GPIO_NUM 1
    #define OPENKNX_GPIO_TYPES OPENKNX_GPIO_T_TCA9555
    #define OPENKNX_GPIO_ADDRS 0x20
    #define OPENKNX_GPIO_INTS 0x08

    #define OPENKNX_GPIO_WIRE Wire1
    #define OPENKNX_GPIO_SDA 6
    #define OPENKNX_GPIO_SCL 7
    #define OPENKNX_GPIO_CLOCK 400000
#endif

#ifdef BOARD_AB_SMARTHOUSE_SA_REG6_6CH_CS
    #define DEVICE_ID "AB-SWA-6CH-CS"
    #define HARDWARE_NAME "AB-SWA-6CH-CS"
    #define DEVICE_NAME "AB-SmartHouse Switch Actuator 6x with Current Sense, 6 TE"

    #define INFO_LED_PIN 3
    #define INFO_LED_PIN_ACTIVE_ON HIGH
    #define PROG_LED_PIN 2
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN 9
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

    #define KNX_UART_NUM 1
    #define KNX_UART_TX_PIN 4
    #define KNX_UART_RX_PIN 5
    #define SAVE_INTERRUPT_PIN 0

    #define OPENKNX_SWA_CHANNEL_COUNT 6
    #define OPENKNX_SWA_SET_PINS 17, 19, 21, 23, 25 ,27
    #define OPENKNX_SWA_RESET_PINS 16, 18, 20, 22, 24, 26
    #define OPENKNX_SWA_MEASURE_EN_PINS 0x0201, 0x0203, 0x0205, 0x020C, 0x020A, 0x0208
    #define OPENKNX_SWA_MEASURE_CS_PINS 0x0200, 0x0202, 0x0204, 0x020D, 0x020B, 0x0209
    #define OPENKNX_SWA_SET_ACTIVE_ON HIGH
    #define OPENKNX_SWA_RESET_ACTIVE_ON HIGH
    #define OPENKNX_SWA_MEASURE_EN_ACTIVE_ON LOW
    #define OPENKNX_SWA_MEASURE_CS_ACTIVE_ON LOW
    #define OPENKNX_SWA_BISTABLE_IMPULSE_LENGTH 50
    #define OPENKNX_SWA_HAS_FRONT_PLATE

    #define OPENKNX_SWA_STATUS_PINS 0x0100, 0x0101, 0x0102, 0x0103, 0x0104, 0x0105
    #define OPENKNX_SWA_STATUS_ACTIVE_ON HIGH
    #define OPENKNX_SWA_SWITCH_PINS 0x0115, 0x0114, 0x0113, 0x0112, 0x0111, 0x0110
    #define OPENKNX_SWA_SWITCH_ACTIVE_ON LOW

    #define OPENKNX_SWA_VOLTAGE_SENSE_PIN 29

    #define OPENKNX_SWA_TEMPSENS_ADDR 0x48

    #define OPENKNX_SWA_BL0942_SPI SPI1
    #define OPENKNX_SWA_BL0942_SPI_SCK_PIN 10
    #define OPENKNX_SWA_BL0942_SPI_TX_PIN 11
    #define OPENKNX_SWA_BL0942_SPI_RX_PIN 12
    
    #define OPENKNX_GPIO_NUM 2
    #define OPENKNX_GPIO_TYPES OPENKNX_GPIO_T_TCA9555, OPENKNX_GPIO_T_TCA9555
    #define OPENKNX_GPIO_ADDRS 0x20, 0x24
    #define OPENKNX_GPIO_INTS 0x08, 0x00

    #define OPENKNX_GPIO_WIRE Wire1
    #define OPENKNX_GPIO_SDA 6
    #define OPENKNX_GPIO_SCL 7
    #define OPENKNX_GPIO_CLOCK 400000
#endif

#ifdef BOARD_REG1_SA_4xSELV
    #define OKNXHW_REG1_SA_4XSELV
    #include "OpenKNXHardware.h"

    #define OPENKNX_SWA_CHANNEL_COUNT 4
    #define OPENKNX_SWA_SET_PINS 0x0106, 0x0104, 0x0100, 0x0102
    #define OPENKNX_SWA_RESET_PINS 0x0107, 0x0105, 0x0101, 0x0103

    //#define OPENKNX_SWA_STATUS_PINS 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF
    //#define OPENKNX_SWA_STATUS_ACTIVE_ON HIGH

    //#define OPENKNX_SWA_SWITCH_PINS 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF
    //#define OPENKNX_SWA_SWITCH_ACTIVE_ON HIGH

    #define OPENKNX_GPIO_NUM 1
    #define OPENKNX_GPIO_TYPES OKNXHW_REG1_APP_SA_4xSELV_TCA_TYPE
    #define OPENKNX_GPIO_ADDRS OKNXHW_REG1_APP_SA_4xSELV_TCA_ADDR
    #define OPENKNX_GPIO_INTS 0xFF

    #define OPENKNX_GPIO_WIRE Wire
    #define OPENKNX_GPIO_CLOCK 400000
    #define OPENKNX_GPIO_SDA OKNXHW_REG1_APP_SA_4xSELV_TCA_SDA
    #define OPENKNX_GPIO_SCL OKNXHW_REG1_APP_SA_4xSELV_TCA_SCL
#endif