#define INFO_LED_PIN 11
#define INFO_LED_PIN_ACTIVE_ON HIGH
#define PROG_LED_PIN 10
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 9
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

#define KNX_UART_TX_PIN 12
#define KNX_UART_RX_PIN 13
#define SAVE_INTERRUPT_PIN 0

#define RELAY_CH0_SET   28
#define RELAY_CH0_RESET 29
#define RELAY_CH1_SET   26
#define RELAY_CH1_RESET 27
#define RELAY_CH2_SET   24
#define RELAY_CH2_RESET 25
#define RELAY_CH3_SET   22
#define RELAY_CH3_RESET 23
#define RELAY_CH4_SET   20
#define RELAY_CH4_RESET 21
#define RELAY_CH5_SET   18
#define RELAY_CH5_RESET 19
#define RELAY_CH6_SET   16
#define RELAY_CH6_RESET 17
#define RELAY_CH7_SET   14
#define RELAY_CH7_RESET 15

#define RELAY_SET_ACTIVE_ON HIGH
#define RELAY_RESET_ACTIVE_ON HIGH

#define INOUT_SDA 6
#define INOUT_SCL 7
#define INOUT_INT 8