

#ifdef BOARD_REG1_SA_4xSELV


#define OKNXHW_REG1_SA_4XSELV
#include "OpenKNXHardware.h"

#define OPENKNX_SWA_CHANNEL_COUNT 4
#define OPENKNX_SWA_SET_PINS 0x0106, 0x0104, 0x0100, 0x0102
#define OPENKNX_SWA_RESET_PINS 0x0107, 0x0105, 0x0101, 0x0103


//#define OPENKNX_SWA_STATUS_PINS 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF
//#define OPENKNX_SWA_STATUS_ACTIVE_ON HIGH

//#define OPENKNX_SWA_SWITCH_PINS 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF
//#define OPENKNX_SWA_SWITCH_ACTIVE_ON HIGH


#define OPENKNX_GPIO_NUM 1
#define OPENKNX_GPIO_TYPES OKNXHW_REG1_APP_SA_4xSELV_TCA_TYPE
#define OPENKNX_GPIO_ADDRS OKNXHW_REG1_APP_SA_4xSELV_TCA_ADDR
#define OPENKNX_GPIO_INTS 0xFF

#define OPENKNX_GPIO_WIRE Wire
#define OPENKNX_GPIO_CLOCK 400000
#define OPENKNX_GPIO_SDA OKNXHW_REG1_APP_SA_4xSELV_TCA_SDA
#define OPENKNX_GPIO_SCL OKNXHW_REG1_APP_SA_4xSELV_TCA_SCL


#endif





