#pragma once

#define MAIN_Version "b17ad7f"
#define KNX_Version "2.2.1+1b646c1"
#define MODULE_LogicModule_Version "3.7.1+1ba35cb"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 7
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 55
#define MODULE_Common_Version "1.4.3+2f8171e"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 4
#define MODULE_Common_Version_Revision 3
#define MODULE_Common_ETS 20
#define MODULE_SwitchActuator_Version "0.1.0+c35288a"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
#define MODULE_FileTransferModule_Version "0.1.1+75e4c00"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 1
#define MODULE_FileTransferModule_ETS 1
#define MODULE_GPIOModule_Version "0.0.0+b95bb8c"
#define MODULE_GPIOModule_Version_Major 0
#define MODULE_GPIOModule_Version_Minor 0
#define MODULE_GPIOModule_Version_Revision 0
#define MODULE_GPIOModule_ETS 0
