#pragma once

#define MAIN_Version "2fc6c95"
#define KNX_Version "2.3.1+49c1072"
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_Common_Version "1.8.0+9f044df"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 8
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 24
#define MODULE_LogicModule_Version "4.3.0+45e2159"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 3
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 67
#define MODULE_FunctionBlocks_Version "0.10.0+e8ec058"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 10
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 10
#define MODULE_SwitchActuator_Version "0.1.0+f2845c4"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 1
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 1
